import { Project, LineItem } from "./types";

export const mockProjects: Project[] = [
  {
    id: "mspace-brendale-s2",
    name: "M-Space Brendale — Stage 2",
    type: "industrial",
    location: "Brendale, Brisbane",
    totalArea: 3200,
    estimatedBudget: 4200000,
    status: "pre-construction",
    createdAt: "2025-11-15",
  },
  {
    id: "parc-bulimba",
    name: "PARC Bulimba — Residences",
    type: "residential",
    location: "Bulimba, Brisbane",
    totalArea: 2800,
    estimatedBudget: 6800000,
    status: "estimating",
    createdAt: "2026-01-08",
  },
  {
    id: "vicinity-robina",
    name: "Vicinity Robina — Commercial",
    type: "mixed-use",
    location: "Robina, Gold Coast",
    totalArea: 1500,
    estimatedBudget: 2100000,
    status: "estimating",
    createdAt: "2026-02-20",
  },
];

export const mockLineItems: LineItem[] = [
  // ── Preliminaries ──
  {
    id: "li-001",
    projectId: "mspace-brendale-s2",
    category: "Preliminaries",
    description: "Site establishment & temporary fencing",
    unit: "lot",
    quantity: 1,
    unitRate: 28500,
    totalCost: 28500,
    supplier: "QBuild Services",
    status: "contracted",
    source: "manual",
    notes: "",
  },
  {
    id: "li-002",
    projectId: "mspace-brendale-s2",
    category: "Preliminaries",
    description: "Scaffolding — full perimeter access",
    unit: "m²",
    quantity: 1800,
    unitRate: 32,
    totalCost: 57600,
    supplier: "Aussie Scaffolds",
    status: "quoted",
    source: "manual",
    notes: "12-week hire included",
  },
  {
    id: "li-003",
    projectId: "mspace-brendale-s2",
    category: "Preliminaries",
    description: "Project management & site supervision",
    unit: "lot",
    quantity: 1,
    unitRate: 145000,
    totalCost: 145000,
    supplier: null,
    status: "estimated",
    source: "manual",
    notes: "36-week programme",
  },

  // ── Site Works ──
  {
    id: "li-004",
    projectId: "mspace-brendale-s2",
    category: "Site Works",
    description: "Bulk excavation — cut to fill",
    unit: "m³",
    quantity: 2800,
    unitRate: 55,
    totalCost: 154000,
    supplier: "Boral Quarries",
    status: "contracted",
    source: "manual",
    notes: "",
  },
  {
    id: "li-005",
    projectId: "mspace-brendale-s2",
    category: "Site Works",
    description: "Detailed excavation for footings",
    unit: "m³",
    quantity: 420,
    unitRate: 65,
    totalCost: 27300,
    supplier: "Boral Quarries",
    status: "contracted",
    source: "manual",
    notes: "",
  },
  {
    id: "li-006",
    projectId: "mspace-brendale-s2",
    category: "Site Works",
    description: "Retaining wall — reinforced block",
    unit: "lm",
    quantity: 85,
    unitRate: 480,
    totalCost: 40800,
    supplier: "Concrib SEQ",
    status: "quoted",
    source: "manual",
    notes: "Max 1.2m height",
  },

  // ── Concrete & Structure ──
  {
    id: "li-007",
    projectId: "mspace-brendale-s2",
    category: "Concrete & Structure",
    description: "Concrete supply — N32 grade for slabs",
    unit: "m³",
    quantity: 480,
    unitRate: 310,
    totalCost: 148800,
    supplier: "Boral Concrete",
    status: "contracted",
    source: "manual",
    notes: "32 MPa, 100mm slump",
  },
  {
    id: "li-008",
    projectId: "mspace-brendale-s2",
    category: "Concrete & Structure",
    description: "Structural steel — portal frames",
    unit: "t",
    quantity: 65,
    unitRate: 5200,
    totalCost: 338000,
    supplier: "Steelforce Australia",
    status: "contracted",
    source: "ai-extracted",
    notes: "Hot-dip galvanised",
  },
  {
    id: "li-009",
    projectId: "mspace-brendale-s2",
    category: "Concrete & Structure",
    description: "Reinforcement steel — mesh & bar",
    unit: "t",
    quantity: 42,
    unitRate: 2800,
    totalCost: 117600,
    supplier: "InfraBuild",
    status: "quoted",
    source: "manual",
    notes: "SL82 mesh + N12/N16 bar",
  },
  {
    id: "li-010",
    projectId: "mspace-brendale-s2",
    category: "Concrete & Structure",
    description: "Formwork to slabs & footings",
    unit: "m²",
    quantity: 650,
    unitRate: 85,
    totalCost: 55250,
    supplier: null,
    status: "estimated",
    source: "manual",
    notes: "",
  },

  // ── Brickwork & Masonry ──
  {
    id: "li-011",
    projectId: "mspace-brendale-s2",
    category: "Brickwork & Masonry",
    description: "Concrete block walls — 200mm series",
    unit: "m²",
    quantity: 1200,
    unitRate: 95,
    totalCost: 114000,
    supplier: "Boral Masonry",
    status: "quoted",
    source: "manual",
    notes: "Core-filled & reinforced",
  },
  {
    id: "li-012",
    projectId: "mspace-brendale-s2",
    category: "Brickwork & Masonry",
    description: "Office partition blockwork — 100mm series",
    unit: "m²",
    quantity: 340,
    unitRate: 78,
    totalCost: 26520,
    supplier: "Boral Masonry",
    status: "estimated",
    source: "manual",
    notes: "",
  },

  // ── Roofing ──
  {
    id: "li-013",
    projectId: "mspace-brendale-s2",
    category: "Roofing",
    description: "Roof sheeting — Colorbond Trimdek",
    unit: "m²",
    quantity: 3400,
    unitRate: 48,
    totalCost: 163200,
    supplier: "Lysaght / BlueScope",
    status: "contracted",
    source: "manual",
    notes: "Windspray colour",
  },
  {
    id: "li-014",
    projectId: "mspace-brendale-s2",
    category: "Roofing",
    description: "Guttering & downpipes — Colorbond Quad",
    unit: "lm",
    quantity: 280,
    unitRate: 42,
    totalCost: 11760,
    supplier: "Lysaght / BlueScope",
    status: "quoted",
    source: "manual",
    notes: "",
  },
  {
    id: "li-015",
    projectId: "mspace-brendale-s2",
    category: "Roofing",
    description: "Roof insulation — R3.0 blanket",
    unit: "m²",
    quantity: 3200,
    unitRate: 18,
    totalCost: 57600,
    supplier: "CSR Bradford",
    status: "quoted",
    source: "manual",
    notes: "Anticon 55 faced",
  },

  // ── Waterproofing ──
  {
    id: "li-016",
    projectId: "mspace-brendale-s2",
    category: "Waterproofing",
    description: "Wet area waterproofing membrane",
    unit: "m²",
    quantity: 380,
    unitRate: 45,
    totalCost: 17100,
    supplier: "Fosroc Australia",
    status: "quoted",
    source: "manual",
    notes: "AS 3740 compliant",
  },
  {
    id: "li-017",
    projectId: "mspace-brendale-s2",
    category: "Waterproofing",
    description: "External wall sarking — breathable membrane",
    unit: "m²",
    quantity: 1400,
    unitRate: 12,
    totalCost: 16800,
    supplier: "CSR Bradford",
    status: "estimated",
    source: "manual",
    notes: "",
  },

  // ── Tiling & Flooring ──
  {
    id: "li-018",
    projectId: "mspace-brendale-s2",
    category: "Tiling & Flooring",
    description: "Office floor tiles — 600x600 porcelain",
    unit: "m²",
    quantity: 640,
    unitRate: 88,
    totalCost: 56320,
    supplier: "Beaumont Tiles",
    status: "quoted",
    source: "ai-extracted",
    notes: "Anti-slip rated",
  },
  {
    id: "li-019",
    projectId: "mspace-brendale-s2",
    category: "Tiling & Flooring",
    description: "Amenities floor tiles — 300x300 non-slip",
    unit: "m²",
    quantity: 190,
    unitRate: 75,
    totalCost: 14250,
    supplier: "Beaumont Tiles",
    status: "quoted",
    source: "ai-extracted",
    notes: "",
  },
  {
    id: "li-020",
    projectId: "mspace-brendale-s2",
    category: "Tiling & Flooring",
    description: "Epoxy floor coating — warehouse areas",
    unit: "m²",
    quantity: 2400,
    unitRate: 42,
    totalCost: 100800,
    supplier: "Rhino Linings",
    status: "estimated",
    source: "manual",
    notes: "2-coat system",
  },

  // ── Plastering & Painting ──
  {
    id: "li-021",
    projectId: "mspace-brendale-s2",
    category: "Plastering & Painting",
    description: "Internal plasterboard — 13mm standard",
    unit: "m²",
    quantity: 2200,
    unitRate: 38,
    totalCost: 83600,
    supplier: "CSR Gyprock",
    status: "quoted",
    source: "manual",
    notes: "Supply & fix",
  },
  {
    id: "li-022",
    projectId: "mspace-brendale-s2",
    category: "Plastering & Painting",
    description: "Internal painting — 2-coat acrylic",
    unit: "m²",
    quantity: 4400,
    unitRate: 18,
    totalCost: 79200,
    supplier: "Dulux Trade",
    status: "estimated",
    source: "manual",
    notes: "Wash & Wear low sheen",
  },
  {
    id: "li-023",
    projectId: "mspace-brendale-s2",
    category: "Plastering & Painting",
    description: "External render — acrylic texture coat",
    unit: "m²",
    quantity: 480,
    unitRate: 62,
    totalCost: 29760,
    supplier: null,
    status: "estimated",
    source: "manual",
    notes: "",
  },

  // ── Joinery & Cabinetry ──
  {
    id: "li-024",
    projectId: "mspace-brendale-s2",
    category: "Joinery & Cabinetry",
    description: "Kitchen joinery — office kitchenettes",
    unit: "ea",
    quantity: 12,
    unitRate: 9500,
    totalCost: 114000,
    supplier: "Laminex / local joiner",
    status: "quoted",
    source: "manual",
    notes: "Stone benchtop, soft-close",
  },
  {
    id: "li-025",
    projectId: "mspace-brendale-s2",
    category: "Joinery & Cabinetry",
    description: "Bathroom vanity units",
    unit: "ea",
    quantity: 24,
    unitRate: 1800,
    totalCost: 43200,
    supplier: "Laminex / local joiner",
    status: "estimated",
    source: "manual",
    notes: "",
  },

  // ── Plumbing ──
  {
    id: "li-026",
    projectId: "mspace-brendale-s2",
    category: "Plumbing",
    description: "Plumbing rough-in — all units",
    unit: "point",
    quantity: 144,
    unitRate: 520,
    totalCost: 74880,
    supplier: "Reece Plumbing",
    status: "contracted",
    source: "manual",
    notes: "12 points per unit",
  },
  {
    id: "li-027",
    projectId: "mspace-brendale-s2",
    category: "Plumbing",
    description: "Plumbing fixtures — supply & install",
    unit: "lot",
    quantity: 12,
    unitRate: 4200,
    totalCost: 50400,
    supplier: "Reece Plumbing",
    status: "quoted",
    source: "manual",
    notes: "Caroma & Dorf fixtures",
  },
  {
    id: "li-028",
    projectId: "mspace-brendale-s2",
    category: "Plumbing",
    description: "Stormwater drainage system",
    unit: "lot",
    quantity: 1,
    unitRate: 68000,
    totalCost: 68000,
    supplier: "Reece Plumbing",
    status: "estimated",
    source: "manual",
    notes: "PVC drainage to council main",
  },

  // ── Electrical ──
  {
    id: "li-029",
    projectId: "mspace-brendale-s2",
    category: "Electrical",
    description: "Electrical rough-in — all units",
    unit: "point",
    quantity: 288,
    unitRate: 95,
    totalCost: 27360,
    supplier: "Clipsal / Schneider",
    status: "contracted",
    source: "manual",
    notes: "24 points per unit",
  },
  {
    id: "li-030",
    projectId: "mspace-brendale-s2",
    category: "Electrical",
    description: "Switchboard & metering — per unit",
    unit: "ea",
    quantity: 12,
    unitRate: 3800,
    totalCost: 45600,
    supplier: "NHP Electrical",
    status: "quoted",
    source: "manual",
    notes: "Individual metering",
  },
  {
    id: "li-031",
    projectId: "mspace-brendale-s2",
    category: "Electrical",
    description: "LED lighting — warehouse high bay",
    unit: "ea",
    quantity: 96,
    unitRate: 420,
    totalCost: 40320,
    supplier: "Pierlite",
    status: "quoted",
    source: "manual",
    notes: "200W LED high bay",
  },
  {
    id: "li-032",
    projectId: "mspace-brendale-s2",
    category: "Electrical",
    description: "Data & communications cabling",
    unit: "point",
    quantity: 96,
    unitRate: 185,
    totalCost: 17760,
    supplier: null,
    status: "estimated",
    source: "manual",
    notes: "Cat6A to each unit",
  },

  // ── HVAC / Mechanical ──
  {
    id: "li-033",
    projectId: "mspace-brendale-s2",
    category: "HVAC / Mechanical",
    description: "Split system A/C — office areas",
    unit: "kW",
    quantity: 180,
    unitRate: 420,
    totalCost: 75600,
    supplier: "Daikin Australia",
    status: "quoted",
    source: "manual",
    notes: "15kW per office",
  },
  {
    id: "li-034",
    projectId: "mspace-brendale-s2",
    category: "HVAC / Mechanical",
    description: "Warehouse exhaust ventilation",
    unit: "ea",
    quantity: 24,
    unitRate: 1850,
    totalCost: 44400,
    supplier: "Fantech",
    status: "estimated",
    source: "manual",
    notes: "Industrial roof fans",
  },
  {
    id: "li-035",
    projectId: "mspace-brendale-s2",
    category: "HVAC / Mechanical",
    description: "Fire services — detection & sprinklers",
    unit: "lot",
    quantity: 1,
    unitRate: 185000,
    totalCost: 185000,
    supplier: "Wormald",
    status: "quoted",
    source: "manual",
    notes: "BCA compliant, class 7/8",
  },

  // ── External Works ──
  {
    id: "li-036",
    projectId: "mspace-brendale-s2",
    category: "External Works",
    description: "Concrete driveway & hardstand",
    unit: "m²",
    quantity: 1600,
    unitRate: 120,
    totalCost: 192000,
    supplier: "Boral Concrete",
    status: "quoted",
    source: "manual",
    notes: "Heavy-duty industrial spec",
  },
  {
    id: "li-037",
    projectId: "mspace-brendale-s2",
    category: "External Works",
    description: "Line marking & signage",
    unit: "lot",
    quantity: 1,
    unitRate: 12000,
    totalCost: 12000,
    supplier: null,
    status: "estimated",
    source: "manual",
    notes: "",
  },
  {
    id: "li-038",
    projectId: "mspace-brendale-s2",
    category: "External Works",
    description: "Landscaping — turf & garden beds",
    unit: "m²",
    quantity: 450,
    unitRate: 65,
    totalCost: 29250,
    supplier: "Daleys Turf",
    status: "estimated",
    source: "manual",
    notes: "Sir Walter turf + native planting",
  },
  {
    id: "li-039",
    projectId: "mspace-brendale-s2",
    category: "External Works",
    description: "Security fencing — 2.1m palisade",
    unit: "lm",
    quantity: 320,
    unitRate: 185,
    totalCost: 59200,
    supplier: "Bluedog Fences",
    status: "quoted",
    source: "manual",
    notes: "Powder-coated black",
  },

  // ── Finishes & Fixtures ──
  {
    id: "li-040",
    projectId: "mspace-brendale-s2",
    category: "Finishes & Fixtures",
    description: "Roller doors — 4.8m x 4.5m industrial",
    unit: "ea",
    quantity: 12,
    unitRate: 4800,
    totalCost: 57600,
    supplier: "B&D Doors",
    status: "contracted",
    source: "manual",
    notes: "Auto with remote",
  },
  {
    id: "li-041",
    projectId: "mspace-brendale-s2",
    category: "Finishes & Fixtures",
    description: "Commercial entry doors — aluminium framed",
    unit: "ea",
    quantity: 12,
    unitRate: 3200,
    totalCost: 38400,
    supplier: "AWS Aluminium",
    status: "quoted",
    source: "manual",
    notes: "",
  },
  {
    id: "li-042",
    projectId: "mspace-brendale-s2",
    category: "Finishes & Fixtures",
    description: "Aluminium windows — office areas",
    unit: "m²",
    quantity: 210,
    unitRate: 520,
    totalCost: 109200,
    supplier: "AWS Aluminium",
    status: "quoted",
    source: "manual",
    notes: "Powder-coated, double glazed",
  },

  // ── Contingency & Margins ──
  {
    id: "li-043",
    projectId: "mspace-brendale-s2",
    category: "Contingency & Margins",
    description: "Construction contingency (5%)",
    unit: "lot",
    quantity: 1,
    unitRate: 175000,
    totalCost: 175000,
    supplier: null,
    status: "estimated",
    source: "manual",
    notes: "5% of construction cost",
  },
  {
    id: "li-044",
    projectId: "mspace-brendale-s2",
    category: "Contingency & Margins",
    description: "Builder's margin (8%)",
    unit: "lot",
    quantity: 1,
    unitRate: 280000,
    totalCost: 280000,
    supplier: null,
    status: "estimated",
    source: "manual",
    notes: "",
  },
  {
    id: "li-045",
    projectId: "mspace-brendale-s2",
    category: "Contingency & Margins",
    description: "Escalation allowance (2.5%)",
    unit: "lot",
    quantity: 1,
    unitRate: 87500,
    totalCost: 87500,
    supplier: null,
    status: "estimated",
    source: "manual",
    notes: "12-month programme",
  },

  // ── PARC Bulimba line items ──
  {
    id: "li-p2-001",
    projectId: "parc-bulimba",
    category: "Preliminaries",
    description: "Site establishment & hoarding",
    unit: "lot",
    quantity: 1,
    unitRate: 85000,
    totalCost: 85000,
    supplier: "QBuild Services",
    status: "estimated",
    source: "manual",
    notes: "Heritage streetscape hoarding",
  },
  {
    id: "li-p2-002",
    projectId: "parc-bulimba",
    category: "Concrete & Structure",
    description: "Post-tensioned slabs — 8 levels",
    unit: "m²",
    quantity: 2800,
    unitRate: 185,
    totalCost: 518000,
    supplier: null,
    status: "estimated",
    source: "manual",
    notes: "",
  },
  {
    id: "li-p2-003",
    projectId: "parc-bulimba",
    category: "Tiling & Flooring",
    description: "Engineered timber flooring — living areas",
    unit: "m²",
    quantity: 1400,
    unitRate: 145,
    totalCost: 203000,
    supplier: "Preference Floors",
    status: "estimated",
    source: "manual",
    notes: "European oak",
  },
  {
    id: "li-p2-004",
    projectId: "parc-bulimba",
    category: "Joinery & Cabinetry",
    description: "Kitchen joinery — luxury specification",
    unit: "ea",
    quantity: 24,
    unitRate: 14500,
    totalCost: 348000,
    supplier: null,
    status: "estimated",
    source: "manual",
    notes: "Reconstituted stone, integrated appliances",
  },
  {
    id: "li-p2-005",
    projectId: "parc-bulimba",
    category: "Electrical",
    description: "Electrical fit-out — luxury specification",
    unit: "lot",
    quantity: 24,
    unitRate: 12500,
    totalCost: 300000,
    supplier: null,
    status: "estimated",
    source: "manual",
    notes: "Home automation ready",
  },
  {
    id: "li-p2-006",
    projectId: "parc-bulimba",
    category: "HVAC / Mechanical",
    description: "Ducted air conditioning — all apartments",
    unit: "ea",
    quantity: 24,
    unitRate: 8500,
    totalCost: 204000,
    supplier: "Daikin Australia",
    status: "estimated",
    source: "manual",
    notes: "Concealed ducted",
  },
  {
    id: "li-p2-007",
    projectId: "parc-bulimba",
    category: "Finishes & Fixtures",
    description: "Aluminium balustrades — glass infill",
    unit: "lm",
    quantity: 480,
    unitRate: 650,
    totalCost: 312000,
    supplier: null,
    status: "estimated",
    source: "manual",
    notes: "12mm toughened glass",
  },
  {
    id: "li-p2-008",
    projectId: "parc-bulimba",
    category: "Contingency & Margins",
    description: "Construction contingency (7.5%)",
    unit: "lot",
    quantity: 1,
    unitRate: 450000,
    totalCost: 450000,
    supplier: null,
    status: "estimated",
    source: "manual",
    notes: "",
  },

  // ── Vicinity Robina line items ──
  {
    id: "li-p3-001",
    projectId: "vicinity-robina",
    category: "Preliminaries",
    description: "Design development & DA costs",
    unit: "lot",
    quantity: 1,
    unitRate: 120000,
    totalCost: 120000,
    supplier: null,
    status: "estimated",
    source: "manual",
    notes: "Council fees included",
  },
  {
    id: "li-p3-002",
    projectId: "vicinity-robina",
    category: "Site Works",
    description: "Demolition of existing structure",
    unit: "lot",
    quantity: 1,
    unitRate: 85000,
    totalCost: 85000,
    supplier: null,
    status: "estimated",
    source: "manual",
    notes: "Asbestos survey complete",
  },
  {
    id: "li-p3-003",
    projectId: "vicinity-robina",
    category: "Concrete & Structure",
    description: "Structural frame — steel & concrete",
    unit: "lot",
    quantity: 1,
    unitRate: 480000,
    totalCost: 480000,
    supplier: null,
    status: "estimated",
    source: "manual",
    notes: "Preliminary estimate",
  },
  {
    id: "li-p3-004",
    projectId: "vicinity-robina",
    category: "Electrical",
    description: "Electrical services — base build",
    unit: "lot",
    quantity: 1,
    unitRate: 195000,
    totalCost: 195000,
    supplier: null,
    status: "estimated",
    source: "manual",
    notes: "",
  },
  {
    id: "li-p3-005",
    projectId: "vicinity-robina",
    category: "Contingency & Margins",
    description: "Development contingency (10%)",
    unit: "lot",
    quantity: 1,
    unitRate: 190000,
    totalCost: 190000,
    supplier: null,
    status: "estimated",
    source: "manual",
    notes: "Early-stage estimate",
  },
];
